
// Objective-C API for talking to the following Go packages
//
//	Asyn_CBDC/goCBDC
//
// File is generated by gomobile bind. Do not edit.
#ifndef __GoCBDC_FRAMEWORK_H__
#define __GoCBDC_FRAMEWORK_H__

#include "GoCBDC.objc.h"
#include "Universe.objc.h"

#endif
