// Objective-C API for talking to Asyn_CBDC/goCBDC Go package.
//   gobind -lang=objc Asyn_CBDC/goCBDC
//
// File is generated by gobind. Do not edit.

#ifndef __GoCBDC_H__
#define __GoCBDC_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


FOUNDATION_EXPORT NSString* _Nonnull GoCBDCGO_CBDC(void);

#endif
